apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-petclinic
  namespace: argocd
spec:
  project: np-hepapi
  source:
    repoURL: 'https://nexus.hepapi.com/repository/nexushelmrepository/'
    chart: 	spring-petclinic-dev
    targetRevision: '1.0.51'
  destination:
    name: "np-dev"
    namespace: dev
  syncPolicy:
    automated: 
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
