apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: eventbus-dev
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: np-dev
            name: dev
            chartVersion: 0.11.4

  template:
    metadata:
      name: '{{cluster}}-eventbus'
    spec:
      project: default

      destination:
        namespace: dev
        name: '{{cluster}}'

      syncPolicy:
        automated:
          selfHeal: true
          prune: false
        syncOptions:
          - Validate=true
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true

      source:
        repoURL: oci://registry-1.docker.io/cloudpirates
        chart: rabbitmq
        targetRevision: '{{chartVersion}}'
        helm:
          values: |
            fullnameOverride: "eventbus"

            image:
              registry: docker.io
              repository: rabbitmq
              tag: "4.2.2-management"

            auth:
              enabled: true
              username: admin
              password: eventbus-dev-pass
              erlangCookie: eventbus-dev-cookie

            persistence:
              enabled: true
              size: 1Gi

            memoryHighWatermark:
              enabled: true
              type: relative
              value: 0.6

            containerSecurityContext:
              allowPrivilegeEscalation: false
              runAsNonRoot: true
              runAsUser: 999
              runAsGroup: 999
              readOnlyRootFilesystem: false

            podSecurityContext:
              fsGroup: 999
