apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: eventbus-dev
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: np-dev
            name: dev
            version: 16.0.14
  template:
    metadata:
      name: '{{cluster}}-eventbus'
    spec:
      project: default
      destination:
        namespace: dev
        name: '{{cluster}}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: false
        syncOptions:
          - Validate=true
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
      source:
        repoURL: https://charts.bitnami.com/bitnami
        targetRevision: '{{version}}'
        chart: rabbitmq
        helm:
          values: |
            fullnameOverride: "eventbus"

            global:
              security:
                allowInsecureImages: true

            image:
              registry: docker.io
              repository: bitnamilegacy/rabbitmq
              tag: 4.1.3-debian-12-r1

            auth:
              username: "guest"
              password: "guest"

            extraConfiguration: |
              loopback_users = none

            volumePermissions:
              enabled: true

            persistence:
              enabled: true
              size: 1Gi
