apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: redis-cart-dev
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: np-dev
            name: dev
            version: 23.2.5
            ns: 'namespace=~"database"'
  template:
    metadata:
      name: '{{cluster}}-redis-cart'
    spec:
      project: default
      destination:
        namespace: database
        name: '{{cluster}}'

      syncPolicy:
        automated:
          selfHeal: true
          prune: false
        syncOptions:
          - Validate=true
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true

      source:
        repoURL: https://charts.bitnami.com/bitnami
        targetRevision: '{{version}}'
        chart: redis
        helm:
          values: |
            global:
              security:
                allowInsecureImages: true

            image:
              registry: docker.io
              repository: bitnamilegacy/redis
              tag: "8.2.1-debian-12-r0"
              pullPolicy: IfNotPresent

            architecture: standalone

            # No password
            auth:
              enabled: false

            master:
              service:
                ports:
                  redis: 6379
                servicePort: 6379
                name: redis-cart

              # ✅ Disable AOF / RDB / persistence
              redisExtraFlags:
                - "--appendonly no"
                - "--save ''"
                - "--dir /tmp"
                - "--appenddirname appendonlydir"

              # ✅ Writable dir for runtime files
              extraVolumes:
                - name: tmp
                  emptyDir: {}
              extraVolumeMounts:
                - name: tmp
                  mountPath: /tmp

              # ✅ Allow running as root to avoid permission errors
              podSecurityContext:
                enabled: true
                runAsUser: 0
                runAsGroup: 0
                fsGroup: 0

              containerSecurityContext:
                enabled: true
                allowPrivilegeEscalation: true
                readOnlyRootFilesystem: false

              resources:
                requests:
                  cpu: "70m"
                  memory: "200Mi"
                limits:
                  cpu: "125m"
                  memory: "256Mi"

            persistence:
              enabled: false
